.TH IQRFGD2-INTERFACE-INIT 1 2021-07-03 "IQRF Gateway Daemon Interface Init" "IQRF GW Manual"
.SH NAME
iqrfgd2-interface-init \- initializes interface configuration for IQRF Gateway Daemon
.SH DESCRIPTION
The
.B iqrfgd2-interface-init
command initializes IQRF Gateway Daemon configuration with placeholders depending on gateway.
.SH SYNOPSIS
\fBiqrfgd2-interface-init\fP
.SH LICENCE
This program is licensed under the GNU Affero General Public License v3.0.
.SH COPYRIGHT
.nf
Copyright 2015\-2025 IQRF Tech s.r.o.
Copyright 2019\-2025 MICRORISC s.r.o.
.fi
