.TH IQRFGD2 1 2019-11-26 "IQRF Gateway Daemon v2.2.0" "IQRF GW Manual"
.SH NAME
iqrfgd2\- start IQRF Gateway Daemon
.SH DESCRIPTION
The
.B iqrfgd2
command starts IQRF Gateway Daemon.
.SH SYNOPSIS
iqrfgd2 [command] [configuration]
.SH COMMANDS
.nf
.TP
.BR iqrfgd2 " \fIversion\fP"
Shows IQRF Gateway Daemon's version
.TP
.BR iqrfgd2 " \fIconfig.json\fP"
Starts IQRF Gateway Daemon
.fi
.SH LICENCE
This program is licensed under Apache License version 2.0.
.SH COPYRIGHT
.nf
Copyright 2017 MICRORISC s.r.o.
Copyright 2017 IQRF Tech s.r.o.
.fi
