# Copyright 2015-2026 IQRF Tech s.r.o.
# Copyright 2019-2026 MICRORISC s.r.o.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

stages:
  - test
  - build-packages
  - deploy-api

.ssh-template:
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - git checkout -B "$CI_COMMIT_REF_NAME" "$CI_COMMIT_SHA"
    - git submodule update --init --recursive

api-testing:
  stage: test
  allow_failure: true
  image: docker:latest
  services:
    - name: docker:dind
      command:
        - "--dns=10.11.18.159"
        - "--insecure-registry=docker-hub-proxy.nexus.iqrf.internal:80"
        - "--registry-mirror=http://docker-hub-proxy.nexus.iqrf.internal:80"
  before_script:
    - apk add --no-cache docker-compose
    - docker info
  script:
    - docker compose -f apitesting.docker-compose.yml up --build --abort-on-container-exit --exit-code-from tests
  tags:
    - docker
    - daemon-api-testing
  variables:
    DOCKER_HOST: "unix:///runner/services/docker/docker.sock"
    DOCKER_TLS_CERTDIR: "/certs"

# API
api-deploy:
  image: iqrftech/debian-c-builder:debian-trixie-amd64
  stage: deploy-api
  only:
    - master
  extends: .ssh-template
  dependencies: []
  script:
    - rsync -hrvz --delete -e ssh api/ www-deploy@icinga.iqrf.org:/data/nginx/apidocs/iqrf-gateway-daemon/latest/json/iqrf/
  tags:
    - linux, amd64

include:
  - template: Security/SAST.gitlab-ci.yml
  # Tests
  - component: gitlab.iqrf.org/open-source/gitlab-ci-components/test-cpp-ctest-coverage@master
    inputs:
      job_name: coverage
      distributions:
        - debian-bullseye
        - debian-bookworm
        - debian-trixie
        - debian-forky
      project_dir: '.'
      before_script:
        - mkdir deploy
        - git clone --depth=1 --recurse-submodules https://gitlab.iqrf.org/open-source/iqrf-gateway-daemon-utils/shape.git
        - git clone --depth=1 --recurse-submodules https://gitlab.iqrf.org/open-source/iqrf-gateway-daemon-utils/shapeware.git
        - cmake -Bshape-build -Hshape -DBUILD_TESTING:BOOL=TRUE -DCMAKE_BUILD_TYPE=Debug -DSHAPE_DEPLOY:PATH=$PWD/deploy -DUSE_CCACHE=TRUE
        - cmake --build shape-build --target install
        - cmake -Bshapeware-build -Hshapeware -Dshape_DIR:PATH=`pwd`/shape-build -DBUILD_TESTING:BOOL=TRUE -DBUILD_CURL_REST_API:BOOL=FALSE -DBUILD_MQTT:BOOL=FALSE -DBUILD_WS_SERVER:BOOL=FALSE -DCMAKE_BUILD_TYPE=Debug -DUSE_CCACHE=TRUE
        - cmake --build shapeware-build --target install
      cmake_options: -DBUILD_TESTING:BOOL=TRUE -Dshape_DIR:PATH=`pwd`/shape-build -Dshapeware_DIR:PATH=`pwd`/shapeware-build
      cmake_build_options: --target install
  # Packages
  - component: gitlab.iqrf.org/open-source/gitlab-ci-components/build-jsonnnet-deb-packages@master
    inputs:
      job_name: build-jsonnet
      stage: build-packages
  - component: gitlab.iqrf.org/open-source/gitlab-ci-components/trigger-build-jobs-deb-packages@master
    inputs:
      job_name: trigger-build-deb-packages
      stage: build-packages
      jsonnet_build_job: build-jsonnet
