BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `Node` (
    `Mid` 	INTEGER NOT NULL PRIMARY KEY UNIQUE,
	`Hwpid`	INTEGER NOT NULL,
    `HwpidVer`	INTEGER NOT NULL,
    `OsBuild`	INTEGER NOT NULL,
    `OsVer`	INTEGER NOT NULL,
    `DpaVer` INTEGER NOT NULL,
    `ModeStd` INTEGER NOT NULL,
    `StdAndLpNet` INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS `Bonded` (
	`Nadr` INTEGER NOT NULL PRIMARY KEY UNIQUE,
	`Dis` INTEGER NOT NULL,
	`Mid` INTEGER UNIQUE,
	`Enm` INTEGER NOT NULL,
	FOREIGN KEY(`Mid`) REFERENCES `Node`(`Mid`)
);

CREATE TABLE IF NOT EXISTS `Perifery` (
	`Mid` INTEGER NOT NULL,
	`Per` INTEGER NOT NULL,
	FOREIGN KEY(`Mid`) REFERENCES `Node`(`Mid`)
);

CREATE TABLE IF NOT EXISTS `Sensor` (
	`Mid`	INTEGER NOT NULL,
	`Idx`	INTEGER NOT NULL,
    `Sid`	TEXT NOT NULL,
    `Stype`	INTEGER NOT NULL,
    `Name`	TEXT NOT NULL,
    `SName`	TEXT NOT NULL,
    `Unit`	TEXT NOT NULL,
    `Dplac`	INTEGER NOT NULL,
	`Frc2bit`	INTEGER NOT NULL,
	`Frc1byte`	INTEGER NOT NULL,
	`Frc2byte`	INTEGER NOT NULL,
	`Frc4byte`	INTEGER NOT NULL,
	FOREIGN KEY(`Mid`) REFERENCES `Node`(`Mid`)
);

COMMIT;
