BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `Node` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Nadr`	INTEGER NOT NULL,
	`Hwpid`	INTEGER NOT NULL,
    `HwpidVer`	INTEGER NOT NULL,
    `OsBuild`	INTEGER NOT NULL,
    `OsVer`	INTEGER NOT NULL,
    `Mid` 	INTEGER NOT NULL,
    `DpaVersion` INTEGER NOT NULL,
    `ModeStd` INTEGER NOT NULL,
    `StdAndLpNetwork` INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS `Bonded` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`NodeId` INTEGER NOT NULL,
	FOREIGN KEY(`NodeId`) REFERENCES `Node`(`Id`)
);

CREATE TABLE IF NOT EXISTS `Discovered` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`NodeId` INTEGER NOT NULL,
	FOREIGN KEY(`NodeId`) REFERENCES `Node`(`Id`)
);

COMMIT;
