#!/usr/bin/env python3

import json
import ssl
import websocket

ws = websocket.create_connection(
  'ws://localhost:1438',
  sslopt={'cert_reqs': ssl.CERT_NONE}
)
response = ws.recv()
ws.close()

notification = json.loads(response)
if notification["data"]["operMode"] != "operational":
  raise SystemExit(1)

raise SystemExit(0)
