src/start-IqrfDaemon/configuration/*.json                   usr/share/iqrf-gateway/default/daemon
src/start-IqrfDaemon/configuration-LinDeploy/*.json         usr/share/iqrf-gateway/default/daemon
src/start-IqrfDaemon/cfgSchemas                             usr/share/iqrf-gateway/default/daemon
src/start-IqrfDaemon/schedulerSchema                        usr/share/iqrf-gateway/default/daemon
src/start-IqrfDaemon/metaData                               usr/share/iqrf-gateway/default/daemon