#!/bin/bash
# After remove script for iqrf-gateway-daemon

set -e

daemon_remove_config() {
  rm -rf /etc/iqrf-gateway-daemon/
}

daemon_remove_data() {
  rm -rf /usr/share/iqrf-gateway-daemon/
  rm -rf /var/cache/iqrf-gateway-daemon/
}

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
  daemon_remove_data
  daemon_remove_config
fi

if [ "$1" = "remove" ]; then
  if [ -x "/usr/bin/deb-systemd-helper" ]; then
    deb-systemd-helper mask iqrf-gateway-daemon.service >/dev/null || true
  fi
fi

if [ "$1" = "purge" ]; then
  if [ -x "/usr/bin/deb-systemd-helper" ]; then
    deb-systemd-helper purge iqrf-gateway-daemon.service >/dev/null || true
    deb-systemd-helper unmask iqrf-gateway-daemon.service >/dev/null || true
  fi
fi
