#!/bin/bash

# Copyright 2015-2023 IQRF Tech s.r.o.
# Copyright 2019-2023 MICRORISC s.r.o.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# After install script for iqrf-gateway-daemon

set -e

openssl_create_ca() {
	CA_DIR="/etc/iqrf-gateway-daemon/certs/core"
	if [ ! -d ${CA_DIR} ]; then
		mkdir -p ${CA_DIR}
	fi

	if ! find /etc/iqrf-gateway-daemon/certs/core/ -type f -not -newermt "2020-04-12T00:00:00" -exec false {} +; then
		rm -rf "${CA_DIR}/cert.pem" "${CA_DIR}/privkey.pem"
	fi

	if [ ! -f ${CA_DIR}/cert.pem ] || [ ! -f ${CA_DIR}/privkey.pem ]; then
		openssl ecparam -name secp384r1 -genkey -param_enc named_curve \
			-out ${CA_DIR}/privkey.pem
		openssl req -new -x509 -sha256 -nodes -days 3650 \
			-subj "/CN=IQRF Gateway/C=CZ/ST=Hradec Kralove Region/L=Jicin/O=IQRF Tech s.r.o." \
			-key ${CA_DIR}/privkey.pem -out ${CA_DIR}/cert.pem
		chmod 600 ${CA_DIR}/*.pem
	fi
}

remove_old_dirs() {
	rm -rf /etc/iqrfgd2
	rm -rf /var/cache/iqrfgd2
	rm -rf /usr/lib/iqrfgd2
	rm -rf /usr/share/iqrfgd2
	rm -f /lib/systemd/system/iqrfgd2.service
}

configure_gateway() {
	bash /usr/bin/iqrfgd2-config-init "/etc/iqrf-gateway-daemon/"
	sh /usr/bin/iqrfgd2-interface-init
}

if [ "$1" = "configure" ]; then
	openssl_create_ca
	remove_old_dirs
	configure_gateway
fi

#DEBHELPER#