#!/bin/bash

# Copyright 2015-2025 IQRF Tech s.r.o.
# Copyright 2019-2025 MICRORISC s.r.o.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Before install script

set -e

if [ -d "/etc/iqrf-gateway-daemon/cfgSchemas" ]; then
    rm -rf /etc/iqrf-gateway-daemon/cfgSchemas
fi

if [ -d "/usr/share/iqrf-gateway-daemon/DB" ]; then
    rm -rf /usr/share/iqrf-gateway-daemon/DB
fi

if [ -d "/var/cache/iqrf-gateway-daemon/scheduler/schema" ]; then
    rm -rf /var/cache/iqrf-gateway-daemon/scheduler/schema
fi

#DEBHELPER#
