#!/bin/sh

set -e

# Automatically added by dh_installinit/13.1
if [ -x "/etc/init.d/iqrf-gateway-daemon" ] && [ "$1" = remove ]; then
  invoke-rc.d iqrf-gateway-daemon stop || exit 1
fi
# End automatically added section

# Automatically added by dh_systemd_start/13.1
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
  deb-systemd-invoke stop 'iqrf-gateway-daemon.service' >/dev/null || true
fi
# End automatically added section

if [ "$1" = "upgrade" ]; then
  # Remove old IQRF Repository cache directories
  for dir in server companies manufacturers osdpa products standards packages; do
    rm -rf /var/cache/iqrf-gateway-daemon/iqrfRepoCache/${dir:?}
  done
fi
