#!/bin/sh

set -e

#DEBHELPER#

if [ "$1" = "upgrade" ]; then
  # Remove old IQRF Repository cache directories
  for dir in server companies manufacturers osdpa products standards packages; do
    rm -rf /var/cache/iqrf-gateway-daemon/iqrfRepoCache/${dir:?}
  done
fi
