# Site settings
baseURL = "http://apidocs.iqrfsdk.org/iqrf-gateway-daemon"
languageCode = "en-us"
title = "IQRF Gateway Daemon v2 API"
theme = "hugo-simpledoc-theme"

[blackfriday]
#  angledQuotes = true
#  fractions = false
#  plainIDAnchors = true
#  smartlists = true
#  extensions = ["hardLineBreak"]

# Top menu
#[[menu.top]]
#    name = "IQRF Gateway Daemon GitHub Repository"
#    weight = 10
#    url = "https://github.com/iqrfsdk/iqrf-gateway-daemon"
#[[menu.top]]
#    name = "IQRF Gateway Daemon Webapp Github Repository"
#    weight = 20
#    url = "https://github.com/iqrfsdk/iqrf-gateway-daemon/webapp"
#[[menu.top]]
#    name = "IQRF Gateway Daemon Examples Github Repository"
#    weight = 30
#    url = "https://github.com/iqrfsdk/iqrf-gateway-daemon/examples"

# Site parameters
[params]

    # Meta
    description = "API description - JSON schemas and examples (work in progress)"
    author = "Rostislav Spinar"
    keywords = "iqrf daemon 2, json schemas, api description, simple documentation"
    
    # Header
    # If not set, site title and meta description will be shown.
    # You may use markdown here
    headerTitle = ""
    headerDescription = ""
    
    # Back-to-top button name
    bttButton = ""
