@startuml
title Iqrf Daemon Components with respect to Devices Repository

skinparam component {
  FontSize 13
  BackgroundColor<<Apache>> Red
  BorderColor<<Apache>> #FF6655
  FontName Courier
  FontStyle bold
  BorderColor black
  BackgroundColor gold
  ArrowFontStyle italic
  ArrowFontName Arial
  ArrowColor #FF6655
  ArrowFontColor #777777
}

skinparam note {
  FontSize 9
  FontName Arial
  BorderColor Gray
  BackgroundColor white
  FontStyle italic
  ArrowFontName Arial
}


component [JsonStdDev] as C35
component [JsonEmbedPer] as C34
component [JsonNtwMgm] as C36
component [JsEngine] as C40
component [RestClient] as C50
component [JsCache] as C41
component [Scheduler] as C60


C40 -u- I40
C41 -d- I41
C50 -d- I50

C34 .u.> I41
C35 .u.> I41
C36 .u.> I41
C34 .d.> I40
C35 .d.> I40
C36 .d.> I40


C41 .l.> I50
C41 .r.> I60
C60 -- I60

interface "IJsEngine" as I40
interface "IJsCache" as I41
interface "IRestClient" as I50
interface "ISchedulerService" as I60

@enduml
