@startuml
title Iqrf Daemon Components with respect to Async API

skinparam component {
  FontSize 13
  BackgroundColor<<Apache>> Red
  BorderColor<<Apache>> #FF6655
  FontName Courier
  FontStyle bold
  BorderColor black
  BackgroundColor gold
  ArrowFontStyle italic
  ArrowFontName Arial
  ArrowColor #FF6655
  ArrowFontColor #777777
}

skinparam note {
  FontSize 9
  FontName Arial
  BorderColor Gray
  BackgroundColor white
  FontStyle italic
  ArrowFontName Arial
}

component [LwsMessaging] as C10
component [MqttMessaging] as C11
component [MqMessaging] as C12

component [JsonHub] as C20

component [JsonDpa] as C30
component [JsonEmbedPer] as C34
component [JsonStdDev] as C35
component [JsonNtwMgm] as C36
component [JsonCfgMgm] as C37
component [JsonSched] as C38
component [Json...] as C39

component [Scheduler] as C60

C10 -- I10
C11 -- I10
C12 -- I10
C38 -r- I10

C20 .u.> I10

C20 -- I20

C30 .u.> I20
C34 .u.> I20
C35 .u.> I20
C36 .u.> I20
C37 .l.> I20
C38 .d.> I20
C39 .u.> I20

C38 .d.> I60

C60 -u- I60

interface "IMessagingService" as I10
interface "IMessagingSplitterService" as I20
interface "ISchedulerService" as I60

@enduml
