//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v9.10.57.0 (Newtonsoft.Json v11.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------

namespace iqmeshNetwork_WriteTrConf_Request
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.10.57.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class IqmeshNetwork_WriteTrConf_Request 
    {
        /// <summary>IQMESH Network management - Write TR configuration request.</summary>
        [Newtonsoft.Json.JsonProperty("mType", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public IqmeshNetwork_WriteTrConf_RequestMType MType { get; set; }
    
        [Newtonsoft.Json.JsonProperty("data", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public Data Data { get; set; } = new Data();
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static IqmeshNetwork_WriteTrConf_Request FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<IqmeshNetwork_WriteTrConf_Request>(data);
        }
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.10.57.0 (Newtonsoft.Json v11.0.0.0)")]
    public enum IqmeshNetwork_WriteTrConf_RequestMType
    {
        [System.Runtime.Serialization.EnumMember(Value = "iqmeshNetwork_WriteTrConf")]
    
        IqmeshNetwork_WriteTrConf = 0,
    
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.10.57.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class Data 
    {
        /// <summary>Message identification for binding request with response.</summary>
        [Newtonsoft.Json.JsonProperty("msgId", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public string MsgId { get; set; }
    
        /// <summary>Number of repetitions of DPA messages.</summary>
        [Newtonsoft.Json.JsonProperty("repeat", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int? Repeat { get; set; } = 1;
    
        /// <summary>Restart required after writing the configuration.</summary>
        [Newtonsoft.Json.JsonProperty("restart", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool? Restart { get; set; } = true;
    
        [Newtonsoft.Json.JsonProperty("req", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public Req Req { get; set; } = new Req();
    
        /// <summary>Flag that includes additional parameters in the response.</summary>
        [Newtonsoft.Json.JsonProperty("returnVerbose", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool? ReturnVerbose { get; set; }
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static Data FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<Data>(data);
        }
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.10.57.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class Req 
    {
        /// <summary>Device address(es) to write the configuration to. Broadcast address is also allowed.</summary>
        [Newtonsoft.Json.JsonProperty("deviceAddr", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.ObjectModel.ObservableCollection<int> DeviceAddr { get; set; } = new System.Collections.ObjectModel.ObservableCollection<int>();
    
        /// <summary>Used RF band.</summary>
        [Newtonsoft.Json.JsonProperty("rfBand", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string RfBand { get; set; }
    
        /// <summary>Main RF channel A of the main network. Valid numbers depend on used RF band.</summary>
        [Newtonsoft.Json.JsonProperty("rfChannelA", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int? RfChannelA { get; set; }
    
        /// <summary>Same as above but second B channel. Used at RFPGM only.</summary>
        [Newtonsoft.Json.JsonProperty("rfChannelB", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int? RfChannelB { get; set; }
    
        /// <summary>Main RF channel A of the optional subordinate network in case the node also plays a role of the coordinator of such network. Valid numbers depend on used RF band.</summary>
        [Newtonsoft.Json.JsonProperty("rfSubChannelA", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int? RfSubChannelA { get; set; }
    
        /// <summary>Same as above but second B channel.</summary>
        [Newtonsoft.Json.JsonProperty("rfSubChannelB", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int? RfSubChannelB { get; set; }
    
        /// <summary>RF output power. Valid numbers 0-7.</summary>
        [Newtonsoft.Json.JsonProperty("txPower", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int? TxPower { get; set; }
    
        /// <summary>RF signal filter. Valid numbers 0-64.</summary>
        [Newtonsoft.Json.JsonProperty("rxFilter", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int? RxFilter { get; set; }
    
        /// <summary>Timeout for receiving RF packets at LP mode at N device.</summary>
        [Newtonsoft.Json.JsonProperty("lpRxTimeout", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int? LpRxTimeout { get; set; }
    
        /// <summary>A nonzero value specifies an alternative DPA service mode channel.</summary>
        [Newtonsoft.Json.JsonProperty("rfPgmAltChannel", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int? RfPgmAltChannel { get; set; }
    
        /// <summary>If sets, then activates RFPGM invoking by TR module reset.</summary>
        [Newtonsoft.Json.JsonProperty("rfPgmEnableAfterReset", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool? RfPgmEnableAfterReset { get; set; }
    
        /// <summary>If sets, then terminates RFPGM automatically ~1 minute after reset.</summary>
        [Newtonsoft.Json.JsonProperty("rfPgmTerminateAfter1Min", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool? RfPgmTerminateAfter1Min { get; set; }
    
        /// <summary>If sets, then terminates RFPGM by dedicated pin of the TR module.</summary>
        [Newtonsoft.Json.JsonProperty("rfPgmTerminateMcuPin", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool? RfPgmTerminateMcuPin { get; set; }
    
        /// <summary>If sets, then enables single or dual channel function.</summary>
        [Newtonsoft.Json.JsonProperty("rfPgmDualChannel", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool? RfPgmDualChannel { get; set; }
    
        /// <summary>RFPGM receiving mode setting. If set, then LP (low power) Rx mode is used during RFPGM. Otherwise STD (standard) Rx mode is used.</summary>
        [Newtonsoft.Json.JsonProperty("rfPgmLpMode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool? RfPgmLpMode { get; set; }
    
        /// <summary>Read only. Indicates that the last RFPGM has successfully been completed.</summary>
        [Newtonsoft.Json.JsonProperty("rfPgmIncorrectUpload", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool? RfPgmIncorrectUpload { get; set; }
    
        /// <summary>If set, then a Custom DPA handler is called in case of an event.</summary>
        [Newtonsoft.Json.JsonProperty("customDpaHandler", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool? CustomDpaHandler { get; set; }
    
        /// <summary>If set, then Node device can be controlled by a SPI or UART interface.</summary>
        [Newtonsoft.Json.JsonProperty("nodeDpaInterface", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool? NodeDpaInterface { get; set; }
    
        /// <summary>Baud rate of the UART interface if one is used.</summary>
        [Newtonsoft.Json.JsonProperty("uartBaudrate", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int? UartBaudrate { get; set; }
    
        /// <summary>If set, then DPA Autoexec is run at a later stage of the module boot time.</summary>
        [Newtonsoft.Json.JsonProperty("dpaAutoexec", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool? DpaAutoexec { get; set; }
    
        /// <summary>If set, then the Node device does not route packets on the background.</summary>
        [Newtonsoft.Json.JsonProperty("routingOff", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool? RoutingOff { get; set; }
    
        /// <summary>If set, then DPA IO Setup is run at an early stage of the module boot time.</summary>
        [Newtonsoft.Json.JsonProperty("ioSetup", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool? IoSetup { get; set; }
    
        /// <summary>If set, then device receives also peer-to-peer (non-networking) packets and raises PeerToPeer event.</summary>
        [Newtonsoft.Json.JsonProperty("peerToPeer", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool? PeerToPeer { get; set; }
    
        /// <summary>It sets security password. If the field is left completely empty (no characters filled), the default password (16x number 0x00) is used (the same as the default set from the factory.</summary>
        [Newtonsoft.Json.JsonProperty("securityPassword", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string SecurityPassword { get; set; }
    
        /// <summary>It sets security user key. Enter a value up to 16 characters.</summary>
        [Newtonsoft.Json.JsonProperty("securityUserKey", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string SecurityUserKey { get; set; }
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static Req FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<Req>(data);
        }
    
    }
}