@startuml

artifact ProductSpecification
artifact ApiRequirements
artifact SwRequirements
artifact SwDesign
artifact ApiDesign
artifact SwTests
artifact ApiTests

ProductSpecification -d-> ApiRequirements
ProductSpecification -d-> SwRequirements
SwRequirements <-- SwDesign
SwRequirements <-- SwTests
ApiRequirements <-- ApiDesign
ApiRequirements <-- ApiTests

@enduml
