#!/bin/bash

# IQRF Gateway Daemon
# Copyright (C) 2015-2025 IQRF Tech s.r.o., 2019-2025 MICRORISC s.r.o.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

confDir=$1

if [ -f /etc/iqrf-gateway.json ]; then
	gwProduct=$(jq -r '.gwProduct' /etc/iqrf-gateway.json)
	if [[ $gwProduct =~ ^IQD-GW-0[12].?$ ]]; then
		gwId=$(jq -r '.gwId' /etc/iqrf-gateway.json | awk '{print tolower($0)}')
		if [[ $gwProduct =~ ^IQD-GW-01.?$ ]]; then
			gwId="iqdgw01-${gwId}"
			if [ -f "${confDir}iqrf__IqrfSpi.json" ]; then
				jq --unbuffered '.instance = "iqrf::IqrfSpi-/dev/spidev1.0" | .IqrfInterface = "/dev/spidev1.0" | .powerEnableGpioPin = 19 | .busEnableGpioPin = 10 | .pgmSwitchGpioPin = 3' "${confDir}iqrf__IqrfSpi.json" > tmp.json && mv tmp.json "${confDir}iqrf__IqrfSpi.json"
			fi
			if [ -f "${confDir}iqrf__IqrfUart.json" ]; then
				jq --unbuffered '.instance = "iqrf::IqrfUart-/dev/ttyS1" | .IqrfInterface = "/dev/ttyS1" | .powerEnableGpioPin = 19 | .busEnableGpioPin = 10 | .pgmSwitchGpioPin = -1 | .+ {uartReset: true}' "${confDir}iqrf__IqrfUart.json" > tmp.json && mv tmp.json "${confDir}iqrf__IqrfUart.json"
			fi
		elif [[ $gwProduct =~ ^IQD-GW-02.?$ ]]; then
			gwId="iqdgw02-${gwId}"
			if [ -f "${confDir}iqrf__IqrfSpi.json" ]; then
				jq --unbuffered '.instance = "iqrf::IqrfSpi-/dev/spidev1.0" | .IqrfInterface = "/dev/spidev1.0" | .powerEnableGpioPin = 19 | .busEnableGpioPin = -1 | .pgmSwitchGpioPin = 3 | .+ {spiEnableGpioPin: 10, uartEnableGpioPin: 6, i2cEnableGpioPin: 7}' "${confDir}iqrf__IqrfSpi.json" > tmp.json && mv tmp.json "${confDir}iqrf__IqrfSpi.json"
			fi
			if [ -f "${confDir}iqrf__IqrfUart.json" ]; then
				jq --unbuffered '.instance = "iqrf::IqrfUart-/dev/ttyS1" | .IqrfInterface = "/dev/ttyS1" | .powerEnableGpioPin = 19 | .busEnableGpioPin = -1 | .pgmSwitchGpioPin = -1 | .+ {i2cEnableGpioPin: 7, uartEnableGpioPin: 6, spiEnableGpioPin: 10, uartReset: true}' "${confDir}iqrf__IqrfUart.json" > tmp.json && mv tmp.json "${confDir}iqrf__IqrfUart.json"
			fi
		fi
		if [ -f "${confDir}iqrf__JsonSplitter.json" ]; then
				jq --unbuffered --arg gwId "$gwId" '.insId = $gwId' "${confDir}iqrf__JsonSplitter.json" > tmp.json && mv tmp.json "${confDir}iqrf__JsonSplitter.json"
			fi
		if [ -f "${confDir}iqrf__MqttMessaging.json" ]; then
			rqTopic=$(jq -r '.TopicRequest' "${confDir}iqrf__MqttMessaging.json")
			rspTopic=$(jq -r '.TopicResponse' "${confDir}iqrf__MqttMessaging.json")
			if [ "$rqTopic" == "Iqrf/DpaRequest" ] && [ "$rspTopic" = "Iqrf/DpaResponse" ]; then
				jq --unbuffered --arg gwId "$gwId" '.ClientId = $gwId | .TopicRequest = "gateway/" + $gwId + "/iqrf/requests" | .TopicResponse = "gateway/" + $gwId + "/iqrf/responses"' "${confDir}iqrf__MqttMessaging.json" > tmp.json && mv tmp.json "${confDir}iqrf__MqttMessaging.json"
			fi
		fi
		if [ -f "${confDir}iqrf__IdeCounterpart.json" ]; then
			jq --unbuffered --arg gwProduct "$gwProduct" '.gwIdentModeByte = 34 | .gwIdentName = $gwProduct' "${confDir}iqrf__IdeCounterpart.json" > tmp.json && mv tmp.json "${confDir}iqrf__IdeCounterpart.json"
		fi
	elif [[ $gwProduct = "Unipi Iris Zulu" ]]; then
		if [ -f "${confDir}iqrf__IqrfSpi.json" ]; then
			jq --unbuffered '.instance = "iqrf::IqrfSpi-/dev/spidev1.0" | .IqrfInterface = "/dev/spidev1.0" | .powerEnableGpioPin = 511 | .busEnableGpioPin = -1 | .pgmSwitchGpioPin = 510 | .+ {i2cEnableGpioPin: 509, spiEnableGpioPin: 508, uartEnableGpioPin: 505}' "${confDir}iqrf__IqrfSpi.json" > tmp.json && mv tmp.json "${confDir}iqrf__IqrfSpi.json"
		fi
		if [ -f "${confDir}iqrf__IqrfUart.json" ]; then
			jq --unbuffered '.instance = "iqrf::IqrfUart-/dev/ttymxc3" | .IqrfInterface = "/dev/ttymxc3" | .powerEnableGpioPin = 511 | .busEnableGpioPin = -1 | .pgmSwitchGpioPin = 510 | .+ {i2cEnableGpioPin: 509, spiEnableGpioPin: 508, uartEnableGpioPin: 505, uartReset: true}' "${confDir}iqrf__IqrfUart.json" > tmp.json && mv tmp.json "${confDir}iqrf__IqrfUart.json"
		fi
	fi
fi
