#!/usr/bin/env python3

# Copyright 2015-2025 IQRF Tech s.r.o.
# Copyright 2019-2025 MICRORISC s.r.o.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from pathlib import Path
import json

cdc = 'iqrf::IqrfCdc'
spi = 'iqrf::IqrfSpi'
uart = 'iqrf::IqrfUart'
gw_file = Path('/etc/iqrf-gateway.json')
cfg_file = Path('/etc/iqrf-gateway-daemon/config.json')

def get_component_name(interface: str) -> None:
  match interface:
    case 'cdc':
      return cdc
    case 'spi':
      return spi
    case 'uart':
      return uart

def set_interfaces(iface_component: str) -> None:
  with cfg_file.open(mode='r', encoding='utf-8') as f:
    cfg = json.load(f)
  components = cfg.get('components', [])
  for component in components:
    if component.get('name') in [cdc, spi, uart]:
      component['enabled'] = (component.get('name') == iface_component)
  with cfg_file.open(mode='w', encoding='utf-8') as f:
    json.dump(cfg, f, indent=4)

if not gw_file.exists():
  set_interfaces(spi)
else:
  with gw_file.open(mode='r', encoding='utf-8') as f:
    gw_data = json.load(f)
  component_name = get_component_name(gw_data['gwInterface'])
  set_interfaces(component_name)

