#!/bin/sh

# Copyright 2015-2021 IQRF Tech s.r.o.
# Copyright 2019-2021 MICRORISC s.r.o.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ -f /etc/iqrf-gateway.json ]
then
	propertyExists=$(jq 'has("gwInterface")' /etc/iqrf-gateway.json)
	(($propertyExists)) && interface=$(jq -r '.gwInterface' /etc/iqrf-gateway.json) || interface='spi'
	case $interface in
		cdc)
			sed -i '0,/"{cdc}"/ s//true/' /etc/iqrf-gateway-daemon/config.json
			sed -i '0,/"{spi}"/ s//false/' /etc/iqrf-gateway-daemon/config.json
			sed -i '0,/"{uart}"/ s//false/' /etc/iqrf-gateway-daemon/config.json
			break;;
		spi)
			sed -i '0,/"{cdc}"/ s//false/' /etc/iqrf-gateway-daemon/config.json
			sed -i '0,/"{spi}"/ s//true/' /etc/iqrf-gateway-daemon/config.json
			sed -i '0,/"{uart}"/ s//false/' /etc/iqrf-gateway-daemon/config.json
			break;;
		uart)
			sed -i '0,/"{cdc}"/ s//false/' /etc/iqrf-gateway-daemon/config.json
			sed -i '0,/"{spi}"/ s//false/' /etc/iqrf-gateway-daemon/config.json
			sed -i '0,/"{uart}"/ s//true/' /etc/iqrf-gateway-daemon/config.json
			break;;
		*)
			;;
	esac
else
	sed -i '0,/"{cdc}"/ s//false/' /etc/iqrf-gateway-daemon/config.json
	sed -i '0,/"{spi}"/ s//true/' /etc/iqrf-gateway-daemon/config.json
	sed -i '0,/"{uart}"/ s//false/' /etc/iqrf-gateway-daemon/config.json
fi