#!/bin/sh

# IQRF Gateway Daemon
# Copyright (C) 2015-2025 IQRF Tech s.r.o., 2019-2025 MICRORISC s.r.o.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if [ -f /etc/iqrf-gateway.json ]
then
	propertyExists=$(jq 'has("gwInterface")' /etc/iqrf-gateway.json)
	(($propertyExists)) && interface=$(jq -r '.gwInterface' /etc/iqrf-gateway.json) || interface='spi'
	case $interface in
		cdc)
			sed -i '0,/"{cdc}"/ s//true/' /etc/iqrf-gateway-daemon/config.json
			sed -i '0,/"{spi}"/ s//false/' /etc/iqrf-gateway-daemon/config.json
			sed -i '0,/"{uart}"/ s//false/' /etc/iqrf-gateway-daemon/config.json
			break;;
		spi)
			sed -i '0,/"{cdc}"/ s//false/' /etc/iqrf-gateway-daemon/config.json
			sed -i '0,/"{spi}"/ s//true/' /etc/iqrf-gateway-daemon/config.json
			sed -i '0,/"{uart}"/ s//false/' /etc/iqrf-gateway-daemon/config.json
			break;;
		uart)
			sed -i '0,/"{cdc}"/ s//false/' /etc/iqrf-gateway-daemon/config.json
			sed -i '0,/"{spi}"/ s//false/' /etc/iqrf-gateway-daemon/config.json
			sed -i '0,/"{uart}"/ s//true/' /etc/iqrf-gateway-daemon/config.json
			break;;
		*)
			;;
	esac
else
	sed -i '0,/"{cdc}"/ s//false/' /etc/iqrf-gateway-daemon/config.json
	sed -i '0,/"{spi}"/ s//true/' /etc/iqrf-gateway-daemon/config.json
	sed -i '0,/"{uart}"/ s//false/' /etc/iqrf-gateway-daemon/config.json
fi
