/**
 * Copyright 2015-2026 IQRF Tech s.r.o.
 * Copyright 2019-2026 MICRORISC s.r.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#include <openssl/evp.h>
#include <openssl/rand.h>
#include <openssl/sha.h>
#include <nlohmann/json.hpp>

#include <algorithm>
#include <stdexcept>
#include <vector>

#define SHA3_DIGEST_LEN 32

using json = nlohmann::json;

class CryptoUtils {
  public:

  /**
    * @brief Generate random bytes of specified length
    * @param len Length of data to generate
    * @return Vector of randomly generated bytes
    */
  static std::vector<unsigned char> generateRandomData(std::size_t len) {
    std::vector<unsigned char> buffer(len);
    if (RAND_bytes(buffer.data(), static_cast<int>(len)) != 1) {
      throw std::runtime_error("Failed to generate random bytes.");
    }
    return buffer;
  }

  /**
  * @brief Compute SHA3-256 hash data
  * @param data Data to hash
  * @return Vector of bytes representing hashed data
  */
  static std::vector<unsigned char> sha256Hash(const std::vector<unsigned char>& data) {
    std::vector<unsigned char> hash(SHA3_DIGEST_LEN);
    EVP_MD_CTX* ctx = EVP_MD_CTX_new();
    unsigned int output_len = 0;
    if (!ctx) {
      throw std::runtime_error("Failed to create hashing context.");
    }

    if (EVP_DigestInit_ex(ctx, EVP_sha3_256(), NULL) != 1) {
      EVP_MD_CTX_free(ctx);
      throw std::runtime_error("Failed to initialize digest.");
    }

    if (EVP_DigestUpdate(ctx, data.data(), data.size()) != 1) {
      EVP_MD_CTX_free(ctx);
      throw std::runtime_error("Failed to update digest with key.");
    }

    if (EVP_DigestFinal_ex(ctx, hash.data(), &output_len) != 1) {
      EVP_MD_CTX_free(ctx);
      throw std::runtime_error("Failed to finalize digest.");
    }

    if (output_len != SHA3_DIGEST_LEN) {
      throw std::runtime_error("Unexpected digest len.");
    }

    EVP_MD_CTX_free(ctx);
    return hash;
  }

  /**
  * @brief Encode bytes to base64 string
  * @param data Vector of bytes to encode
  * @return Base64-encoded string
  */
  static std::string base64Encode(const std::vector<unsigned char>& data) {
    int encoded_len = 4 * ((data.size() + 2) / 3);
    std::vector<unsigned char> buffer(encoded_len + 16);
    EVP_ENCODE_CTX *ctx = EVP_ENCODE_CTX_new();
    if (!ctx) {
      throw std::runtime_error("Failed to create encoding context.");
    }
    int encode_len = 0, final_len = 0;

    EVP_EncodeInit(ctx);
    if (
      EVP_EncodeUpdate(
        ctx,
        buffer.data(),
        &encode_len,
        reinterpret_cast<const unsigned char *>(data.data()),
        static_cast<int>(data.size())) != 1
    ) {
      EVP_ENCODE_CTX_free(ctx);
      throw std::runtime_error("Failed to update encode with data.");
    }
    EVP_EncodeFinal(ctx, buffer.data() + encode_len, &final_len);
    encode_len += final_len;
    EVP_ENCODE_CTX_free(ctx);
    std::string result(reinterpret_cast<char *>(buffer.data()), encode_len);
    result.erase(std::remove(result.begin(), result.end(), '\n'), result.end());
    return result;
  }

  /**
  * @brief Decode base64 string into bytes
  * @param data Base64-encoded string
  * @return Vector of decoded bytes
  */
  static std::vector<unsigned char> base64Decode(const std::string& data) {
    std::vector<unsigned char> decoded(data.size());
    EVP_ENCODE_CTX *ctx = EVP_ENCODE_CTX_new();
    if (!ctx) {
      throw std::runtime_error("Failed to create decoding context.");
    }

    int out_len = 0, final_len = 0;
    EVP_DecodeInit(ctx);
    if (
      EVP_DecodeUpdate(
        ctx,
        decoded.data(),
        &out_len,
        reinterpret_cast<const unsigned char *>(data.data()),
        data.size()
      ) < 0
    ) {
      EVP_ENCODE_CTX_free(ctx);
      throw std::runtime_error("Failed to update decode with data.");
    }

    if (EVP_DecodeFinal(ctx, decoded.data() + out_len, &final_len) != 1) {
      EVP_ENCODE_CTX_free(ctx);
      throw std::runtime_error("Failed to finalize decoding.");
    }

    EVP_ENCODE_CTX_free(ctx);
    decoded.resize(out_len + final_len);
    return decoded;
  }
};
