/**
 * Copyright 2015-2026 IQRF Tech s.r.o.
 * Copyright 2019-2026 MICRORISC s.r.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#include <openssl/evp.h>
#include <openssl/rand.h>
#include <openssl/sha.h>
#include <nlohmann/json.hpp>
#include <sodium/core.h>
#include <sodium/crypto_pwhash.h>

#include <algorithm>
#include <stdexcept>
#include <vector>

#define ARGON2ID_HASH_LIMIT 4096U

using json = nlohmann::json;

class CryptoUtils {
public:

  /**
    * @brief Generate random bytes of specified length
    * @param len Length of data to generate
    * @return Vector of randomly generated bytes
    */
  static std::vector<unsigned char> generateRandomBytes(std::size_t len) {
    std::vector<unsigned char> buffer(len);
    if (RAND_bytes(buffer.data(), static_cast<int>(len)) != 1) {
      throw std::runtime_error("Failed to generate random bytes.");
    }
    return buffer;
  }

  /**
   * @brief Compute SHA-256 hash from salt and key
   * @param salt Salt to hash
   * @param key Secret to hash
   * @return Vector of bytes representing hashed salt and secret
   */
  static std::vector<unsigned char> sha256Hash(const std::vector<unsigned char>& salt, const std::vector<unsigned char>& key) {
    std::vector<unsigned char> hash(EVP_MAX_MD_SIZE);
    EVP_MD_CTX* ctx = EVP_MD_CTX_new();
    unsigned int digest_len = 0;
    if (!ctx) {
      throw std::runtime_error("Failed to create hashing context.");
    }

    if (EVP_DigestInit_ex(ctx, EVP_sha256(), NULL) != 1) {
      EVP_MD_CTX_free(ctx);
      throw std::runtime_error("Failed to initialize digest.");
    }

    if (EVP_DigestUpdate(ctx, salt.data(), salt.size()) != 1) {
      EVP_MD_CTX_free(ctx);
      throw std::runtime_error("Failed to update digest with salt.");
    }

    if (EVP_DigestUpdate(ctx, key.data(), key.size()) != 1) {
      EVP_MD_CTX_free(ctx);
      throw std::runtime_error("Failed to update digest with key.");
    }

    if (EVP_DigestFinal_ex(ctx, hash.data(), &digest_len) != 1) {
      EVP_MD_CTX_free(ctx);
      throw std::runtime_error("Failed to finalize digest.");
    }

    EVP_MD_CTX_free(ctx);
    hash.resize(digest_len);
    return hash;
  }

  /**
   * @brief Encode bytes to base64 string
   * @param data Vector of bytes to encode
   * @return Base64-encoded string
   */
  static std::string base64Encode(const std::vector<unsigned char>& data) {
    int encoded_len = 4 * ((data.size() + 2) / 3);
    std::vector<unsigned char> buffer(encoded_len + 16);
    EVP_ENCODE_CTX *ctx = EVP_ENCODE_CTX_new();
    if (!ctx) {
      throw std::runtime_error("Failed to create encoding context.");
    }
    int encode_len = 0, final_len = 0;

    EVP_EncodeInit(ctx);
    if (
      EVP_EncodeUpdate(
        ctx,
        buffer.data(),
        &encode_len,
        reinterpret_cast<const unsigned char *>(data.data()),
        static_cast<int>(data.size())) != 1
    ) {
      EVP_ENCODE_CTX_free(ctx);
      throw std::runtime_error("Failed to update encode with data.");
    }
    EVP_EncodeFinal(ctx, buffer.data() + encode_len, &final_len);
    encode_len += final_len;
    EVP_ENCODE_CTX_free(ctx);
    std::string result(reinterpret_cast<char *>(buffer.data()), encode_len);
    result.erase(std::remove(result.begin(), result.end(), '\n'), result.end());
    return result;
  }

  /**
   * @brief Decode base64 string into bytes
   * @param data Base64-encoded string
   * @return Vector of decoded bytes
   */
  static std::vector<unsigned char> base64Decode(const std::string& data) {
    std::vector<unsigned char> decoded(data.size());
    EVP_ENCODE_CTX *ctx = EVP_ENCODE_CTX_new();
    if (!ctx) {
      throw std::runtime_error("Failed to create decoding context.");
    }

    int out_len = 0, final_len = 0;
    EVP_DecodeInit(ctx);
    if (
      EVP_DecodeUpdate(
        ctx,
        decoded.data(),
        &out_len,
        reinterpret_cast<const unsigned char *>(data.data()),
        data.size()
      ) < 0
    ) {
      EVP_ENCODE_CTX_free(ctx);
      throw std::runtime_error("Failed to update decode with data.");
    }

    if (EVP_DecodeFinal(ctx, decoded.data() + out_len, &final_len) != 1) {
      EVP_ENCODE_CTX_free(ctx);
      throw std::runtime_error("Failed to finalize decoding.");
    }

    EVP_ENCODE_CTX_free(ctx);
    decoded.resize(out_len + final_len);
    return decoded;
  }

  /**
   * Initialize sodium library
   *
   * @throws `std::runtime_error` Thrown if sodium library cannot be initialized
   */
  static void initSodium() {
    if (sodium_init() == -1) {
      throw std::runtime_error("Unable to initialize libsodium.");
    }
  }

  /**
   * Hash data using the argon2id algorithm
   *
   * The algorithm is configured with 2 iterations and 8MB of memory
   *
   * @param data Data to hash
   * @return `std::string` argon2id hash of data
   * @throws `std::runtime_error` Thrown if hashing fails.
   */
  static std::string argon2idHash(const std::string& data) {
    char hashed[crypto_pwhash_STRBYTES];
    if (crypto_pwhash_str(
      hashed,
      data.c_str(),
      data.length(),
      crypto_pwhash_OPSLIMIT_INTERACTIVE,
      crypto_pwhash_MEMLIMIT_MIN
    ) != 0) {
      throw std::runtime_error("Failed to hash data.");
    }
    return {hashed};
  }

  /**
   * Verifies secret against hashed secret
   *
   * @param hashedSecret argon2id hash
   * @param secret Secret to verify against hash
   * @return `bool` Returns `true` if secret matches the hash, `false` otherwise
   */
  static bool argon2idVerify(const std::string& hashedSecret, const std::string& secret) {
    return crypto_pwhash_str_verify(
      hashedSecret.c_str(),
      secret.c_str(),
      secret.size()
    ) == 0;
  }
};
